#tar -czvf jenkins.tar.gz /jenkins
#tar -xzvf jenkins.tar.gz

#also /home/jenkins copypaste :/

- user: name=jenkins comment="Jenkins"
  register: usr
  
- file: path=/opt/jenkins state=directory owner=1000 group=jenkins

- name: Run jenkins
  docker_service:
    project_name: jenkins
    definition:
      version: '2'
      services:
        jenkins:
          image: "jenkins/jenkins:lts"
          ports:
            - "127.0.0.1:8080:8080"
            - "0.0.0.0:50000:50000"
          user: "1000:jenkins"
          environment:
            JAVA_OPTS: "-Dhudson.model.ParametersAction.keepUndefinedParameters=true -Dfile.encoding=UTF8 -Djava.awt.headless=true -Xms1024M -Xmx1024M -Xmn1024M -XX:MaxPermSize=512M -Duser.timezone=Europe/Moscow"
          volumes:
            - /opt/jenkins:/var/jenkins_home
            - /home/jenkins:/home/jenkins
            - /etc/letsencrypt/:/etc/letsencrypt

- name: Import certs to java
  raw: docker exec -it -u root jenkins_jenkins_1 keytool -trustcacerts -keystore /etc/ssl/certs/java/cacerts -storepass changeit -noprompt -importcert -file /etc/letsencrypt/live/ci.lanwen.ru/chain.pem

- name: Backup cert
  raw: docker cp jenkins_jenkins_1:/etc/ssl/certs/java/cacerts /home/jenkins/cacerts
